### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by canercak** [uber-research/go-explore#3]
Hi,
I get the below error when I try to run the code in my 4GB Ram 2 Core CPU mac. Is there a parameter I should change so I can run the code?
 
```
canermac-3:go-explore apple$ sh ./phase1_pitfall_domain.sh
Code hash: 9ee1ab8d43c267b12e33c9c08aaf7b54dd01609de0371fe29ee6d6b52e9b6a1b
Experiment running in ./results//0011_0797eea89ba54609b9157d9f034451a5/
Time (seconds):   0%|                                                                                                           | 0/1800000.0 [00:00<?, ?it/s]
loky.process_executor._RemoteTraceback: 
'''pute steps:   0%|                                                                                                           | 0/1000000000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/apple/miniconda3/envs/projectlife/lib/python3.6/site-packages/loky/process_executor.py", line 391, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/Users/apple/miniconda3/envs/projectlife/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/Users/apple/.Trash/go-explore/goexplore_py/pitfall_env.py", line 82, in __getattr__
    return getattr(self.env, e)
  File "/Users/apple/.Trash/go-explore/goexplore_py/pitfall_env.py", line 82, in __getattr__
    return getattr(self.env, e)
  File "/Users/apple/.Trash/go-explore/goexplore_py/pitfall_env.py", line 82, in __getattr__
    return getattr(self.env, e)
  [Previous line repeated 993 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "goexplore_py/main.py", line 409, in <module>
    reset_cell_on_update=args.reset_cell_on_update)
  File "goexplore_py/main.py", line 288, in run
    _run(base_path=base_path, **kwargs)
  File "goexplore_py/main.py", line 154, in _run
    expl.run_cycle()
  File "/Users/apple/.Trash/go-explore/goexplore_py/goexplore.py", line 298, in run_cycle
    trajectories = [e.data for e in POOL.map(self.process_cell, chosen_cells)]
  File "/Users/apple/.Trash/go-explore/goexplore_py/goexplore.py", line 298, in <listcomp>
    trajectories = [e.data for e in POOL.map(self.process_cell, chosen_cells)]
  File "/Users/apple/miniconda3/envs/projectlife/lib/python3.6/site-packages/loky/process_executor.py", line 794, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/Users/apple/miniconda3/envs/projectlife/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/Users/apple/miniconda3/envs/projectlife/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/apple/miniconda3/envs/projectlife/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
(projectlife) canermac-3:go-explore apple$ 

```

**Comment by canercak** [comment]
just realized that I had to install loky==2.3.1
